### ISSUE TITLE
Not able to edit asset/select focal point

### ISSUE THREAD

**Issue by howells** [workingconcept/cloudflare-craft-plugin#7]
Hi - I seem to have an issue whereby I cannot edit an asset in the CP with this plugin enabled. When I try to save an asset I get a `"Call to a member function delete() on null”` JS alert.

Brad from P&T discovered this was the error:

```
https://github.com/workingconcept/cloudflare-craft-plugin/blob/master/src/services/CloudflareService.php#L212

2018-09-19 13:48:47 [213.86.15.199][652][-][warning][craft\services\AssetTransforms::deleteAllTransformData] Unable to delete the file "/var/www/vhosts/********/releases/1537324925/storage/runtime/assets/sources/1192.png": unlink(/var/www/vhosts/********/releases/1537324925/storage/runtime/assets/sources/1192.png): No such file or directory
2018-09-19 13:48:47 [213.86.15.199][652][-][error][craft\controllers\AssetsController::actionReplaceFile] An error occurred when replacing an asset: Call to a member function delete() on null
2018-09-19 13:48:47 [213.86.15.199][652][-][error][Error] Error: Call to a member function delete() on null in /var/www/vhosts/********/shared/vendor/workingconcept/craft-cloudflare/src/services/CloudflareService.php:212
Stack trace:
#0 /var/www/vhosts/********/shared/vendor/workingconcept/craft-cloudflare/src/Cloudflare.php(131): workingconcept\cloudflare\services\CloudflareService->purgeUrls(Array)
#1 [internal function]: workingconcept\cloudflare\Cloudflare->workingconcept\cloudflare\{closure}(Object(craft\events\ElementEvent))
#2 /var/www/vhosts/********/shared/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(craft\events\ElementEvent))
#3 /var/www/vhosts/********/shared/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterSaveElemen...', Object(craft\events\ElementEvent))
#4 /var/www/vhosts/********/shared/vendor/craftcms/cms/src/services/Elements.php(542): yii\base\Component->trigger('afterSaveElemen...', Object(craft\events\ElementEvent))
#5 /var/www/vhosts/********/shared/vendor/craftcms/cms/src/services/Assets.php(160): craft\services\Elements->saveElement(Object(craft\elements\Asset))
#6 /var/www/vhosts/********/shared/vendor/craftcms/cms/src/controllers/AssetsController.php(219): craft\services\Assets->replaceAssetFile(Object(craft\elements\Asset), '/var/www/vhosts...', 'little-stack-ro...')
...
```

**Comment by mattstein** [comment]
Thanks for reporting this, @howells! It seems that you could only get this error if you've enabled the Cloudflare plugin and haven't supplied it with valid API credentials. Are you getting this error even _with_ valid API details?

**Comment by mattstein** [comment]
This latest release should also sidestep problems if API credentials aren't supplied, which seems like it should be the case regardless: https://github.com/workingconcept/cloudflare-craft-plugin/releases/tag/0.2.1

**Comment by howells** [comment]
Hi - sorry for the delay, yes indeed that was the case! Sorry about that but thanks for the update,

**Comment by mattstein** [comment]
No worries, glad it's all sorted @howells!
